import MentionEditor from '@/components/mentionsEditor'
import Tagify from '@/components/tagifyEditor'
import Tiptap from '@/components/tiptap'
import dynamic from 'next/dynamic'
import Head from 'next/head'

const Editor = dynamic(
  () => import('@/components/remirrorEditor'),
  { ssr: false }
)
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='w-1/2 mx-auto mt-52'>
          <Editor/>
          <Tiptap/>
          <Tagify/>
          <MentionEditor/>
      </main>
    </>
  )
}
